[package]
authors = ["theotherphil"]
edition = "2018"
name = "talks"
version = "0.1.0"

[dependencies]
pulldown-cmark = "0.6.0"
rayon = "*"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
